INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(1, 'balcones', 'A', 'Cristosende', 'BalconesdeMadrid1A.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(2, 'balcones', 'B', 'Castelo de Castro Caldelas', 'BalconesdeMadrid1B.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(3, 'balcones', 'C', 'Calles en San Lourenzo', 'BalconesdeMadrid1C1.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(4, 'balcones', 'C', 'Necrópolis de San Vitor, cerca de San Lourenzo', 'BalconesdeMadrid1C2.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(5, 'balcones', 'D', 'San Adrián: Lugar en el que existió un antiguo monasterio.', 'BalconesdeMadrid1D.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(6, 'balcones', 'E', 'El nombre podría venir de Sakarboudio, la victoria del guerrero Sakar. ', 'BalconesdeMadrid1E1.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(7, 'balcones', 'E', 'Magosto: En noviembre, con la castaña como protagonista. ', 'BalconesdeMadrid1E2.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(8, 'balcones', 'F', 'Según la tradición, descendientes de Noé, llegados hasta Porta Brosmos remontando el río desde el mar, plantaron aquí las primeras viñas de la Ribeira.', 'BalconesdeMadrid1F.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(9, 'balcones', 'G', 'La tradición atribuye numerosos milagros a la Virgen de Cadeiras, que cuenta con gran devoción en la comarca.', 'BalconesdeMadrid1G.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(10, 'balcones', 'H', 'Monforte de Lemos', 'BalconesdeMadrid1H.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(11, 'balcones', 'I', 'A Arriba, Parroquia de Barantes (Sober)', 'BalconesdeMadrid1I.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(12, 'balcones', 'J', 'El desnivel llega en este punto hasta los 450 metros.', '-');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(13, 'cristina', 'A', 'Arco románico que da acceso al monasterio.', 'SantaCristina3A1.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(14, 'cristina', 'A', 'Evangelistas: Marcos (León) y Mateo (Hombre)', 'SantaCristina3A2.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(15, 'cristina', 'A', 'Evangelistas: Juan (Águila) y Lucas (Toro)', 'SantaCristina3A3.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(16, 'cristina', 'B', 'En el acceso principal a la iglesia destaca la decoración de ajedrezado.', 'SantaCristina3B1.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(17, 'cristina', 'B', 'Capitel con tres caras (quizás la santísima trinidad)', 'SantaCristina3B2.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(18, 'cristina', 'C', 'Magnífico rosetón románico construido para iluminar el templo.', 'SantaCristina3C.jpg');
INSERT INTO `mapimage` (`id`, `mapa`, `id_punto`, `descripcion`, `uri`) VALUES(19, 'cristina', 'D', 'El lateral de la iglesia está decorado con esculturas románicas. Muy representativos los ventanales y las figuras de sus capiteles.  ', 'SantaCristina3D.jpg');
